### ISSUE TITLE
deploy open procurement

### ISSUE THREAD

**Issue by OriHoch** [OpenBudget/OpenProcure#12]
* deploy the govbuy theme container which copies the govbuy theme file to /themes
* mount the /themes folder to search and item apps
* deploy the govbuy main page app (see #13)

**Comment by OriHoch** [comment]
@akariv  I tried to add the govbuy theme container but it seems I'm not authorized to do it on docker cloud

**Comment by akariv** [comment]
done.
https://cloud.docker.com/app/budgetkey/service/47feac21-d289-44ca-b26e-563c8f1cfbff/general
