### ISSUE TITLE
Socialmap: add Midot badge to data structure 

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/OpenProcure#15]
On GuideStar, each association should have a "Midot Badge" field with a list of start date - expirations dates.  This will allow us to show whether the organization has a Midot badge and if they do, until when.

Keeping the dates in a list will enable us later to show/explore past data if needed.

**Comment by akariv** [comment]
Where should I take the data from?

**Comment by akariv** [comment]
Issue moved to [OpenBudget/budgetkey-data-pipelines #108](https://github.com/OpenBudget/budgetkey-data-pipelines/issues/108) via [**ZenHub**](https://www.zenhub.com/)
